//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenPrograA_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preguntas
    {
        public int PreguntaID { get; set; }
        public string UsuarioID { get; set; }
        public string Titulo { get; set; }
        public string Pregunta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
