//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenPrograA_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public string UsuarioID { get; set; }
        public string NombreCompleto { get; set; }
        public string Rol { get; set; }
    }
}
